spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          Get the info in the url below jwks_uri value:
#          http://localhost:8081/realms/easybanco/:well-known/openid-configuration
          jwk-set-uri: http://localhost:8081/realms/easybanco/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/easy_banco
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none  #(create, create-drop, validate, update)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

logging:
  level:
    org:
      springframework:
        security:
          web:
#            FilterChainProxy: DEBUG