spring:
#    security:
#        user:
#            name: happy
#            password: qwerty
  datasource:
    url: jdbc:postgresql://localhost:5432/easy_banco
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  #(create, create-drop, validate, update)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
